#############################################################################
# Makefile for building: CenGen
# Generated by qmake (2.01a) (Qt 4.8.2) on: ?? ???. 19 17:09:52 2012
# Project:  CenGen.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile CenGen.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -fno-show-column -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lQtSql -L/usr/lib64 -L/usr/lib64/qt4 -lQtXml -lQtGui -L/usr/X11R6/lib -lQtNetwork -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		cengen.cpp \
		tinformer.cpp \
		cen_viewer.cpp \
		barcode.cpp \
		dbf_informer.cpp \
		dialog.cpp \
		editor.cpp \
		graph.cpp \
		addlinemaster.cpp \
		imagebox.cpp \
		about.cpp \
		mainTableWidget.cpp \
		autozakaz.cpp \
		sellFilterWidget.cpp \
		models/textBox.cpp \
		models/line.cpp \
		models/image.cpp \
		models/good.cpp \
		models/barcodeBox.cpp \
		models/abstract_item.cpp moc_cengen.cpp \
		moc_dialog.cpp \
		moc_editor.cpp \
		moc_addlinemaster.cpp \
		moc_about.cpp \
		moc_mainTableWidget.cpp \
		moc_autozakaz.cpp \
		moc_sellFilterWidget.cpp \
		moc_textBox.cpp \
		moc_line.cpp \
		moc_image.cpp \
		moc_good.cpp \
		moc_barcodeBox.cpp \
		qrc_resource.cpp
OBJECTS       = main.o \
		cengen.o \
		tinformer.o \
		cen_viewer.o \
		barcode.o \
		dbf_informer.o \
		dialog.o \
		editor.o \
		graph.o \
		addlinemaster.o \
		imagebox.o \
		about.o \
		mainTableWidget.o \
		autozakaz.o \
		sellFilterWidget.o \
		textBox.o \
		line.o \
		image.o \
		good.o \
		barcodeBox.o \
		abstract_item.o \
		moc_cengen.o \
		moc_dialog.o \
		moc_editor.o \
		moc_addlinemaster.o \
		moc_about.o \
		moc_mainTableWidget.o \
		moc_autozakaz.o \
		moc_sellFilterWidget.o \
		moc_textBox.o \
		moc_line.o \
		moc_image.o \
		moc_good.o \
		moc_barcodeBox.o \
		qrc_resource.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		CenGen.pro
QMAKE_TARGET  = CenGen
DESTDIR       = 
TARGET        = CenGen

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_addlinemaster.h ui_autozakaz.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CenGen.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtSql.prl \
		/usr/lib64/qt4/libQtCore.prl \
		/usr/lib64/qt4/libQtXml.prl \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtNetwork.prl
	$(QMAKE) -o Makefile CenGen.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtSql.prl:
/usr/lib64/qt4/libQtCore.prl:
/usr/lib64/qt4/libQtXml.prl:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile CenGen.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/CenGen1.0.0 || $(MKDIR) .tmp/CenGen1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/CenGen1.0.0/ && $(COPY_FILE) --parents cengen.h tinformer.h tovar.h bvalidator.h barcode.h cen_viewer.h sql_config.h dbf_config.h db_translator.h sql_validator.h dbf.h dbf_informer.h dialog.h editor.h graph.h addlinemaster.h imagebox.h about.h mainTableWidget.h tnvalidator.h file_worker.h autozakaz.h sellFilterWidget.h models/textBox.h models/line.h models/image.h models/good.h models/barcodeBox.h models/abstract_item.h .tmp/CenGen1.0.0/ && $(COPY_FILE) --parents resource.qrc .tmp/CenGen1.0.0/ && $(COPY_FILE) --parents main.cpp cengen.cpp tinformer.cpp cen_viewer.cpp barcode.cpp dbf_informer.cpp dialog.cpp editor.cpp graph.cpp addlinemaster.cpp imagebox.cpp about.cpp mainTableWidget.cpp autozakaz.cpp sellFilterWidget.cpp models/textBox.cpp models/line.cpp models/image.cpp models/good.cpp models/barcodeBox.cpp models/abstract_item.cpp .tmp/CenGen1.0.0/ && $(COPY_FILE) --parents addlinemaster.ui autozakaz.ui .tmp/CenGen1.0.0/ && $(COPY_FILE) --parents cengen_ru.ts cengen_en.ts .tmp/CenGen1.0.0/ && (cd `dirname .tmp/CenGen1.0.0` && $(TAR) CenGen1.0.0.tar CenGen1.0.0 && $(COMPRESS) CenGen1.0.0.tar) && $(MOVE) `dirname .tmp/CenGen1.0.0`/CenGen1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/CenGen1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_cengen.cpp moc_dialog.cpp moc_editor.cpp moc_addlinemaster.cpp moc_about.cpp moc_mainTableWidget.cpp moc_autozakaz.cpp moc_sellFilterWidget.cpp moc_textBox.cpp moc_line.cpp moc_image.cpp moc_good.cpp moc_barcodeBox.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cengen.cpp moc_dialog.cpp moc_editor.cpp moc_addlinemaster.cpp moc_about.cpp moc_mainTableWidget.cpp moc_autozakaz.cpp moc_sellFilterWidget.cpp moc_textBox.cpp moc_line.cpp moc_image.cpp moc_good.cpp moc_barcodeBox.cpp
moc_cengen.cpp: tinformer.h \
		tovar.h \
		sql_config.h \
		dbf_config.h \
		db_translator.h \
		dbf_informer.h \
		dbf.h \
		barcode.h \
		imagebox.h \
		cen_viewer.h \
		graph.h \
		bvalidator.h \
		sql_validator.h \
		tnvalidator.h \
		dialog.h \
		mainTableWidget.h \
		editor.h \
		models/barcodeBox.h \
		models/abstract_item.h \
		models/textBox.h \
		models/good.h \
		models/image.h \
		models/line.h \
		about.h \
		autozakaz.h \
		sellFilterWidget.h \
		cengen.h
	/usr/bin/moc $(DEFINES) $(INCPATH) cengen.h -o moc_cengen.cpp

moc_dialog.cpp: mainTableWidget.h \
		tovar.h \
		dialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

moc_editor.cpp: models/barcodeBox.h \
		models/abstract_item.h \
		models/textBox.h \
		models/good.h \
		models/image.h \
		models/line.h \
		cen_viewer.h \
		barcode.h \
		imagebox.h \
		tovar.h \
		graph.h \
		editor.h
	/usr/bin/moc $(DEFINES) $(INCPATH) editor.h -o moc_editor.cpp

moc_addlinemaster.cpp: addlinemaster.h
	/usr/bin/moc $(DEFINES) $(INCPATH) addlinemaster.h -o moc_addlinemaster.cpp

moc_about.cpp: about.h
	/usr/bin/moc $(DEFINES) $(INCPATH) about.h -o moc_about.cpp

moc_mainTableWidget.cpp: tovar.h \
		mainTableWidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainTableWidget.h -o moc_mainTableWidget.cpp

moc_autozakaz.cpp: autozakaz.h
	/usr/bin/moc $(DEFINES) $(INCPATH) autozakaz.h -o moc_autozakaz.cpp

moc_sellFilterWidget.cpp: tinformer.h \
		tovar.h \
		sql_config.h \
		dbf_config.h \
		db_translator.h \
		dbf_informer.h \
		dbf.h \
		dialog.h \
		mainTableWidget.h \
		sellFilterWidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) sellFilterWidget.h -o moc_sellFilterWidget.cpp

moc_textBox.cpp: models/abstract_item.h \
		models/textBox.h
	/usr/bin/moc $(DEFINES) $(INCPATH) models/textBox.h -o moc_textBox.cpp

moc_line.cpp: models/abstract_item.h \
		models/line.h
	/usr/bin/moc $(DEFINES) $(INCPATH) models/line.h -o moc_line.cpp

moc_image.cpp: models/abstract_item.h \
		models/image.h
	/usr/bin/moc $(DEFINES) $(INCPATH) models/image.h -o moc_image.cpp

moc_good.cpp: models/abstract_item.h \
		models/good.h
	/usr/bin/moc $(DEFINES) $(INCPATH) models/good.h -o moc_good.cpp

moc_barcodeBox.cpp: models/abstract_item.h \
		models/barcodeBox.h
	/usr/bin/moc $(DEFINES) $(INCPATH) models/barcodeBox.h -o moc_barcodeBox.cpp

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		resources/print.png \
		resources/folder_blue_open.png \
		resources/down.png \
		resources/up.png \
		resources/my.png \
		resources/filter.png \
		resources/button_cancel.png \
		resources/save.png \
		resources/apply.png \
		resources/window_new.png
	/usr/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_addlinemaster.h ui_autozakaz.h
compiler_uic_clean:
	-$(DEL_FILE) ui_addlinemaster.h ui_autozakaz.h
ui_addlinemaster.h: addlinemaster.ui
	/usr/bin/uic addlinemaster.ui -o ui_addlinemaster.h

ui_autozakaz.h: autozakaz.ui
	/usr/bin/uic autozakaz.ui -o ui_autozakaz.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp cengen.h \
		tinformer.h \
		tovar.h \
		sql_config.h \
		dbf_config.h \
		db_translator.h \
		dbf_informer.h \
		dbf.h \
		barcode.h \
		imagebox.h \
		cen_viewer.h \
		graph.h \
		bvalidator.h \
		sql_validator.h \
		tnvalidator.h \
		dialog.h \
		mainTableWidget.h \
		editor.h \
		models/barcodeBox.h \
		models/abstract_item.h \
		models/textBox.h \
		models/good.h \
		models/image.h \
		models/line.h \
		about.h \
		autozakaz.h \
		sellFilterWidget.h \
		file_worker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cengen.o: cengen.cpp cengen.h \
		tinformer.h \
		tovar.h \
		sql_config.h \
		dbf_config.h \
		db_translator.h \
		dbf_informer.h \
		dbf.h \
		barcode.h \
		imagebox.h \
		cen_viewer.h \
		graph.h \
		bvalidator.h \
		sql_validator.h \
		tnvalidator.h \
		dialog.h \
		mainTableWidget.h \
		editor.h \
		models/barcodeBox.h \
		models/abstract_item.h \
		models/textBox.h \
		models/good.h \
		models/image.h \
		models/line.h \
		about.h \
		autozakaz.h \
		sellFilterWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cengen.o cengen.cpp

tinformer.o: tinformer.cpp tinformer.h \
		tovar.h \
		sql_config.h \
		dbf_config.h \
		db_translator.h \
		dbf_informer.h \
		dbf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinformer.o tinformer.cpp

cen_viewer.o: cen_viewer.cpp cen_viewer.h \
		barcode.h \
		imagebox.h \
		tovar.h \
		graph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cen_viewer.o cen_viewer.cpp

barcode.o: barcode.cpp barcode.h \
		imagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o barcode.o barcode.cpp

dbf_informer.o: dbf_informer.cpp dbf_informer.h \
		dbf.h \
		tovar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbf_informer.o dbf_informer.cpp

dialog.o: dialog.cpp dialog.h \
		mainTableWidget.h \
		tovar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

editor.o: editor.cpp editor.h \
		models/barcodeBox.h \
		models/abstract_item.h \
		models/textBox.h \
		models/good.h \
		models/image.h \
		models/line.h \
		cen_viewer.h \
		barcode.h \
		imagebox.h \
		tovar.h \
		graph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editor.o editor.cpp

graph.o: graph.cpp graph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graph.o graph.cpp

addlinemaster.o: addlinemaster.cpp addlinemaster.h \
		ui_addlinemaster.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addlinemaster.o addlinemaster.cpp

imagebox.o: imagebox.cpp imagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagebox.o imagebox.cpp

about.o: about.cpp about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o about.cpp

mainTableWidget.o: mainTableWidget.cpp mainTableWidget.h \
		tovar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainTableWidget.o mainTableWidget.cpp

autozakaz.o: autozakaz.cpp autozakaz.h \
		ui_autozakaz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autozakaz.o autozakaz.cpp

sellFilterWidget.o: sellFilterWidget.cpp sellFilterWidget.h \
		tinformer.h \
		tovar.h \
		sql_config.h \
		dbf_config.h \
		db_translator.h \
		dbf_informer.h \
		dbf.h \
		dialog.h \
		mainTableWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sellFilterWidget.o sellFilterWidget.cpp

textBox.o: models/textBox.cpp models/textBox.h \
		models/abstract_item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textBox.o models/textBox.cpp

line.o: models/line.cpp models/line.h \
		models/abstract_item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o line.o models/line.cpp

image.o: models/image.cpp models/image.h \
		models/abstract_item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o image.o models/image.cpp

good.o: models/good.cpp models/good.h \
		models/abstract_item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o good.o models/good.cpp

barcodeBox.o: models/barcodeBox.cpp models/barcodeBox.h \
		models/abstract_item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o barcodeBox.o models/barcodeBox.cpp

abstract_item.o: models/abstract_item.cpp models/abstract_item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o abstract_item.o models/abstract_item.cpp

moc_cengen.o: moc_cengen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cengen.o moc_cengen.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_editor.o: moc_editor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editor.o moc_editor.cpp

moc_addlinemaster.o: moc_addlinemaster.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addlinemaster.o moc_addlinemaster.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

moc_mainTableWidget.o: moc_mainTableWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainTableWidget.o moc_mainTableWidget.cpp

moc_autozakaz.o: moc_autozakaz.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_autozakaz.o moc_autozakaz.cpp

moc_sellFilterWidget.o: moc_sellFilterWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sellFilterWidget.o moc_sellFilterWidget.cpp

moc_textBox.o: moc_textBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_textBox.o moc_textBox.cpp

moc_line.o: moc_line.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_line.o moc_line.cpp

moc_image.o: moc_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_image.o moc_image.cpp

moc_good.o: moc_good.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_good.o moc_good.cpp

moc_barcodeBox.o: moc_barcodeBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_barcodeBox.o moc_barcodeBox.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

