#############################################################################
# Makefile for building: CenGen
# Generated by qmake (2.01a) (Qt 4.7.4) on: Wed Jan 11 17:28:02 2012
# Project:  CenGen.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile CenGen.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -fno-show-column -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib/qt4
LIBS          = $(SUBLIBS)  -L/usr/lib/qt4 -lQtSql -L/usr/lib/mysql -L/usr/lib/qt4 -lQtXml -lQtGui -L/usr/X11R6/lib -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		cengen.cpp \
		tinformer.cpp \
		cen_viewer.cpp \
		barcode.cpp \
		dbf_informer.cpp \
		dialog.cpp \
		editor.cpp \
		graph.cpp \
		addlinemaster.cpp \
		imagebox.cpp \
		about.cpp moc_cengen.cpp \
		moc_dialog.cpp \
		moc_editor.cpp \
		moc_addlinemaster.cpp \
		moc_about.cpp \
		qrc_resource.cpp
OBJECTS       = main.o \
		cengen.o \
		tinformer.o \
		cen_viewer.o \
		barcode.o \
		dbf_informer.o \
		dialog.o \
		editor.o \
		graph.o \
		addlinemaster.o \
		imagebox.o \
		about.o \
		moc_cengen.o \
		moc_dialog.o \
		moc_editor.o \
		moc_addlinemaster.o \
		moc_about.o \
		qrc_resource.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		CenGen.pro
QMAKE_TARGET  = CenGen
DESTDIR       = 
TARGET        = CenGen

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_cengen.h ui_dialog.h ui_editor.h ui_addlinemaster.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CenGen.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/qt4/libQtSql.prl \
		/usr/lib/qt4/libQtCore.prl \
		/usr/lib/qt4/libQtXml.prl \
		/usr/lib/qt4/libQtGui.prl
	$(QMAKE) -o Makefile CenGen.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/qt4/libQtSql.prl:
/usr/lib/qt4/libQtCore.prl:
/usr/lib/qt4/libQtXml.prl:
/usr/lib/qt4/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile CenGen.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/CenGen1.0.0 || $(MKDIR) .tmp/CenGen1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/CenGen1.0.0/ && $(COPY_FILE) --parents cengen.h tinformer.h tovar.h bvalidator.h barcode.h cen_viewer.h sql_config.h dbf_config.h db_translator.h sql_validator.h dbf.h dbf_informer.h dialog.h editor.h graph.h addlinemaster.h imagebox.h about.h .tmp/CenGen1.0.0/ && $(COPY_FILE) --parents resource.qrc .tmp/CenGen1.0.0/ && $(COPY_FILE) --parents main.cpp cengen.cpp tinformer.cpp cen_viewer.cpp barcode.cpp dbf_informer.cpp dialog.cpp editor.cpp graph.cpp addlinemaster.cpp imagebox.cpp about.cpp .tmp/CenGen1.0.0/ && $(COPY_FILE) --parents cengen.ui dialog.ui editor.ui addlinemaster.ui .tmp/CenGen1.0.0/ && $(COPY_FILE) --parents cengen_ru.ts cengen_en.ts .tmp/CenGen1.0.0/ && (cd `dirname .tmp/CenGen1.0.0` && $(TAR) CenGen1.0.0.tar CenGen1.0.0 && $(COMPRESS) CenGen1.0.0.tar) && $(MOVE) `dirname .tmp/CenGen1.0.0`/CenGen1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/CenGen1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_cengen.cpp moc_dialog.cpp moc_editor.cpp moc_addlinemaster.cpp moc_about.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cengen.cpp moc_dialog.cpp moc_editor.cpp moc_addlinemaster.cpp moc_about.cpp
moc_cengen.cpp: tinformer.h \
		tovar.h \
		sql_config.h \
		dbf_config.h \
		db_translator.h \
		dbf_informer.h \
		dbf.h \
		barcode.h \
		imagebox.h \
		cen_viewer.h \
		graph.h \
		bvalidator.h \
		sql_validator.h \
		dialog.h \
		editor.h \
		addlinemaster.h \
		about.h \
		cengen.h
	/usr/bin/moc $(DEFINES) $(INCPATH) cengen.h -o moc_cengen.cpp

moc_dialog.cpp: dialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

moc_editor.cpp: addlinemaster.h \
		cen_viewer.h \
		barcode.h \
		imagebox.h \
		tovar.h \
		graph.h \
		editor.h
	/usr/bin/moc $(DEFINES) $(INCPATH) editor.h -o moc_editor.cpp

moc_addlinemaster.cpp: addlinemaster.h
	/usr/bin/moc $(DEFINES) $(INCPATH) addlinemaster.h -o moc_addlinemaster.cpp

moc_about.cpp: about.h
	/usr/bin/moc $(DEFINES) $(INCPATH) about.h -o moc_about.cpp

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		resources/print.png \
		resources/folder_blue_open.png \
		resources/down.png \
		resources/up.png \
		resources/my.png \
		resources/button_cancel.png \
		resources/save.png \
		resources/apply.png \
		resources/window_new.png
	/usr/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_cengen.h ui_dialog.h ui_editor.h ui_addlinemaster.h
compiler_uic_clean:
	-$(DEL_FILE) ui_cengen.h ui_dialog.h ui_editor.h ui_addlinemaster.h
ui_cengen.h: cengen.ui
	/usr/bin/uic cengen.ui -o ui_cengen.h

ui_dialog.h: dialog.ui
	/usr/bin/uic dialog.ui -o ui_dialog.h

ui_editor.h: editor.ui
	/usr/bin/uic editor.ui -o ui_editor.h

ui_addlinemaster.h: addlinemaster.ui
	/usr/bin/uic addlinemaster.ui -o ui_addlinemaster.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp cengen.h \
		tinformer.h \
		tovar.h \
		sql_config.h \
		dbf_config.h \
		db_translator.h \
		dbf_informer.h \
		dbf.h \
		barcode.h \
		imagebox.h \
		cen_viewer.h \
		graph.h \
		bvalidator.h \
		sql_validator.h \
		dialog.h \
		editor.h \
		addlinemaster.h \
		about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cengen.o: cengen.cpp cengen.h \
		tinformer.h \
		tovar.h \
		sql_config.h \
		dbf_config.h \
		db_translator.h \
		dbf_informer.h \
		dbf.h \
		barcode.h \
		imagebox.h \
		cen_viewer.h \
		graph.h \
		bvalidator.h \
		sql_validator.h \
		dialog.h \
		editor.h \
		addlinemaster.h \
		about.h \
		ui_cengen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cengen.o cengen.cpp

tinformer.o: tinformer.cpp tinformer.h \
		tovar.h \
		sql_config.h \
		dbf_config.h \
		db_translator.h \
		dbf_informer.h \
		dbf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinformer.o tinformer.cpp

cen_viewer.o: cen_viewer.cpp cen_viewer.h \
		barcode.h \
		imagebox.h \
		tovar.h \
		graph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cen_viewer.o cen_viewer.cpp

barcode.o: barcode.cpp barcode.h \
		imagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o barcode.o barcode.cpp

dbf_informer.o: dbf_informer.cpp dbf_informer.h \
		dbf.h \
		tovar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbf_informer.o dbf_informer.cpp

dialog.o: dialog.cpp dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

editor.o: editor.cpp editor.h \
		addlinemaster.h \
		cen_viewer.h \
		barcode.h \
		imagebox.h \
		tovar.h \
		graph.h \
		ui_editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editor.o editor.cpp

graph.o: graph.cpp graph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graph.o graph.cpp

addlinemaster.o: addlinemaster.cpp addlinemaster.h \
		ui_addlinemaster.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addlinemaster.o addlinemaster.cpp

imagebox.o: imagebox.cpp imagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagebox.o imagebox.cpp

about.o: about.cpp about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o about.cpp

moc_cengen.o: moc_cengen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cengen.o moc_cengen.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_editor.o: moc_editor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editor.o moc_editor.cpp

moc_addlinemaster.o: moc_addlinemaster.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addlinemaster.o moc_addlinemaster.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

